### ISSUE TITLE
add timestamp in notification

### ISSUE THREAD

**Issue by jakobj** [jakobj/kicker_league#12]
add start time of game and end time of game to notifications

**Comment by mschmidt87** [comment]
Could also be stored in the database, to get even more awesome statistics!

**Comment by jakobj** [comment]
both are already stored.

**Comment by jakobj** [comment]
this might be irrelevant, as far as i can see, notifications already have a time stamp by default (provided by android)

**Comment by jakobj** [comment]
i'll close this now. if there is a need to improve the standard way of displaying a timestamp, we can reopen the ticket.
