### ISSUE TITLE
Create TEST mode

### ISSUE THREAD

**Issue by mschmidt87** [jakobj/kicker_league#31]
Since the app has been released now, we need a test mode for further development, where one can enter results without writing to the actual database, but to a test database.

The simplest solution would be to implement a switch in the app to turn on the test mode. This could also be done in the source code itself.

**Comment by jakobj** [comment]
with the new setting activity we could think about running a second webservice on a different port for testing, or introducing a settings, which lets the user choose the database ("league") where the data should be sent to/requested from. the webservice would then delegate different requests to different databases.

**Comment by jakobj** [comment]
since it is now possible to run a webservice on a different port which writes to a seperate database, i close this ticket.
