### ISSUE TITLE
add more information to current game screen: Probabilities and points at stake

### ISSUE THREAD

**Issue by mschmidt87** [jakobj/kicker_league#35]
Add more information to the screen of the current game:
- the winning probability for each team
- the amount of ELO points at stake for each team.

**Comment by jakobj** [comment]
how does this relate to #19 ?

**Comment by mschmidt87** [comment]
My suggestion for #19 would be to create a new screen, which can be accessed by wiping the home screen to the left with the instant ranking of the players. I don't see a close relation to his issue.

**Comment by jakobj** [comment]
never mind. i thought this issue was also referring to displaying the current elo ranking on the "home screen". no relation to #19.

**Comment by mschmidt87** [comment]
Yeah, thinking is hard sometimes.

**Comment by philipp-w** [comment]
On the server side, this functionality must be implemented in the functions 'startgame', 'restartgame' and 'getcurrentgame'. So far it is implemented in 'startgame' and 'restartgame'.

**Comment by mschmidt87** [comment]
This issue was addressed by pull-request #37 .
The design is still preliminary and can be improved.

**Comment by jakobj** [comment]
is it still true that the points at stake are the total points for the team, not for each player? if so, this should be fixed imho.

**Comment by jakobj** [comment]
it would be great if we could display a few (eg 3) of the last games that the current teams have played against each other including the score on the current game screen.

**Comment by mschmidt87** [comment]
I close this ticket because the original requirements are fulfilled and open another ticket for v0.3: #75 .
