### ISSUE TITLE
display ELO numbers only for players with >10 games

### ISSUE THREAD

**Issue by mschmidt87** [jakobj/kicker_league#39]
We should only display ELO numbers for players with >10 games, because the ELO numbers needs some samples to converge to a reasonable value. Of course, the value of 10 is debatable.

For this, the webservice needs to send the number of played games to the app. We can then add a simple check to the app.

**Comment by jakobj** [comment]
is it necessary that the webservice sends the number of games or could it also just return the elo numbers for players with >10 games?

**Comment by mschmidt87** [comment]
Yes, that's also possible of course. It could send a NAN or a string '?' . I guess that's a matter of taste. Anyway we'll have to wait for Phillipp for this.

**Comment by philipp-w** [comment]
The function 'getplayers/' now returns also the games played. If the number of games < 10, it returns (games_played - 10) as elo rating.
I.e. if one player has played 3 games, the functions returns "elo: -7". 

We can check in the app for negative elo numbers and display the remaining games needed to show the real rating.

**Comment by mschmidt87** [comment]
If I type http://dper.de:9898/getplayers/ into my browser, I get the players without the games_played information and players like Susanne with only a few games are still returned with the normal ELO number. Am I missing something here? Is this only implemented for the test mode?

**Comment by philipp-w** [comment]
This was only active in the test mode so far. I did not dare to move it to production, because this changes the behavior of the app significantly.

I now created a backup of the database and the webservice and moved the changes to production.

**Comment by jakobj** [comment]
@mschmidt87: this seems to work on your phone. can you push the changes to master or will this be part of the "big merge"?

**Comment by mschmidt87** [comment]
It will be part of the big merge since it will be very difficult to disentangle this from all other changes.
So stay tuned, it could happen today!!
