### ISSUE TITLE
remove display of elo numbers on player selection screen

### ISSUE THREAD

**Issue by jakobj** [jakobj/kicker_league#43]
the current way of displaying the elo number below the player names is very clear/intuitive. i propose to remove the numbers completely, now that we have a ranking in-app anyway.

**Comment by mschmidt87** [comment]
I don't understand. The current display is clear and intuitive so you want to remove it?

**Comment by jakobj** [comment]
but it is not useful for quickly comparing the relative strengths of players as the relative difference is too small. and if one is not using it anyway, it would make the layout cleaner if the numbers were removed.

**Comment by mschmidt87** [comment]
Okay, I agree. Just found the phrasing somehow contradictive.

**Comment by jakobj** [comment]
uhh. yeah, i meant to say "is NOT very clear/intuitive". working on it.
