### ISSUE TITLE
players table/players ranking is shown twice

### ISSUE THREAD

**Issue by jakobj** [jakobj/kicker_league#49]
for some reason the table for entering players and/or the ranking is created twice. this is most likely due to create_table being called twice.

**Comment by jakobj** [comment]
this bug is difficult to reproduce. i added some changes that might fix it. if it occurs again, please report here the specific circumstances and git checksum.

**Comment by mschmidt87** [comment]
The bug happened when starting the app, for me quite reliably. With your changes, everything seems fine. I think we can close.
