### ISSUE TITLE
App crashes on restart after having left on ranking view

### ISSUE THREAD

**Issue by mschmidt87** [jakobj/kicker_league#58]
If you do the following, the app crashes:
- Open the app
- Go to the ranking
- Leave the app
- Resurrect the app --> Crash

**Comment by jakobj** [comment]
this is due to refresh() of StartGameFragment trying to change properties of the menu. it is called by onResume() which is always called upon resurrection of the app. if a user was on the ranking screen, the menu (of StartGameFragment) is not created hence the app crashed.

**Comment by jakobj** [comment]
the bug is fixed in branch bug/ranking_resurrect, however, not the menu is not properly refreshed when returning from EnterScoreActivity. this leads to the current game button being displayed after a game was canceled (maybe also entered), until a refresh is manually done (e.g., by swiping).

**Comment by mschmidt87** [comment]
Bravely closed via #62 .
