### ISSUE TITLE
Start revenge game does not work

### ISSUE THREAD

**Issue by mschmidt87** [jakobj/kicker_league#77]
When I click on the "revenge game" button, the app starts a game without player names, so no names appear in the EnterGame screen and the push notification is also without names.

**Comment by philipp-w** [comment]
I can't reproduce this issue in the test mode. Is it always happening or just sometimes?

**Comment by mschmidt87** [comment]
Can you try it in normal mode? You can just abort the game afterwards in order to not corrupt the database.

**Comment by mschmidt87** [comment]
I can't reproduce it anymore, so I close.
