### ISSUE TITLE
Sorting for elo or games causes a crash of the app

### ISSUE THREAD

**Issue by philipp-w** [jakobj/kicker_league#78]
In the table view, the app crashes if tapping on 'Games' or 'ELO'.

**Comment by mschmidt87** [comment]
Thanks, good point. Actually, I haven't designed the button for sorting, but thought about adding this features later.
I guess that the reason for the crash is that the app tries to display player info for this buttons, which does not work for obvious reasons. Anyway, I'll fix this and implement the sorting right away.
